export default [
    {
        id: 1,
        on: false,
        emoji: "🍎",
        spanishword: "manzana",
    },
    {
        id: 2,
        on: false,
        emoji: "⚽️",
        spanishword: "pelota",
    },
    {
        id: 3,
        on: false,
        emoji: "🐱",
        spanishword: "gato",
    },
    {
        id: 4,
        on: false,
        emoji: "🐶",
        spanishword: "perro",
    },
    {
        id: 5,
        on: false,
        emoji: "🐘",
        spanishword: "elefante",
    },
    {
        id: 6,
        on: false,
        emoji: "🐟",
        spanishword: "pez",
    },
    {
        id: 7,
        on: false,
        emoji: "🎸",
        spanishword: "guitarra",
    },
    {
        id: 8,
        on: false,
        emoji: "🎩",
        spanishword: "sombrero",
    },
    {
        id: 9,
        on: false,
        emoji: "🍦",
        spanishword: "helado",
    },
    {
        id: 10,
        on: false,
        emoji: "🪼",
        spanishword: "medusa",
    },
    {
        id: 11,
        on: false,
        emoji: "🪁",
        spanishword: "cometa",
    },
    {
        id: 12,
        on: false,
        emoji: "🦁",
        spanishword: "león",
    },
    {
        id: 13,
        on: false,
        emoji: "🌕",
        spanishword: "luna",
    },
    {
        id: 14,
        on: false,
        emoji: "👃",
        spanishword: "nariz",
    },
    {
        id: 15,
        on: false,
        emoji: "🍊",
        spanishword: "naranja",
    },
    {
        id: 16,
        on: false,
        emoji: "🐷",
        spanishword: "cerdo",
    },
    {
        id: 17,
        on: false,
        emoji: "👸",
        spanishword: "reina",
    },
    {
        id: 18,
        on: false,
        emoji: "🌈",
        spanishword: "arcoíris",
    },
    {
        id: 19,
        on: false,
        emoji: "☀️",
        spanishword: "sol",
    },
    {
        id: 20,
        on: false,
        emoji: "🌳",
        spanishword: "árbol",
    },
    {
        id: 21,
        on: false,
        emoji: "☂️",
        spanishword: "paraguas",
    },
    {
        id: 22,
        on: false,
        emoji: "🎻",
        spanishword: "violín",
    },
    {
        id: 23,
        on: false,
        emoji: "🐋",
        spanishword: "ballena",
    },
    {
        id: 24,
        on: false,
        emoji: "🎹",
        spanishword: "xilófono",
    },
    {
        id: 25,
        on: false,
        emoji: "🪀",
        spanishword: "yoyo",
    },
    {
        id: 26,
        on: false,
        emoji: "🦓",
        spanishword: "cebra",
    },
];
