export default [
    {
        id: 1,
        on: false,
        word: "apple",
        emoji: "🍎",
    },
    {
        id: 2,
        on: false,
        word: "ball",
        emoji: "⚽️",
    },
    {
        id: 3,
        on: false,
        word: "cat",
        emoji: "🐱",
    },
    {
        id: 4,
        on: false,
        word: "dog",
        emoji: "🐶",
    },
    {
        id: 5,
        on: false,
        word: "elephant",
        emoji: "🐘",
    },
    {
        id: 6,
        on: false,
        word: "fish",
        emoji: "🐟",
    },
    {
        id: 7,
        on: false,
        word: "guitar",
        emoji: "🎸",
    },
    {
        id: 8,
        on: false,
        word: "hat",
        emoji: "🎩",
    },
    {
        id: 9,
        on: false,
        word: "ice-cream",
        emoji: "🍦",
    },
    {
        id: 10,
        on: false,
        word: "jellyfish",
        emoji: "🪼",
    },
    {
        id: 11,
        on: false,
        word: "kite",
        emoji: "🪁",
    },
    {
        id: 12,
        on: false,
        word: "lion",
        emoji: "🦁",
    },
    {
        id: 13,
        on: false,
        word: "moon",
        emoji: "🌕",
    },
    {
        id: 14,
        on: false,
        word: "nose",
        emoji: "👃",
    },
    {
        id: 15,
        on: false,
        word: "orange",
        emoji: "🍊",
    },
    {
        id: 16,
        on: false,
        word: "pig",
        emoji: "🐷",
    },
    {
        id: 17,
        on: false,
        word: "queen",
        emoji: "👸",
    },
    {
        id: 18,
        on: false,
        word: "rainbow",
        emoji: "🌈",
    },
    {
        id: 19,
        on: false,
        word: "sun",
        emoji: "☀️",
    },
    {
        id: 20,
        on: false,
        word: "tree",
        emoji: "🌳",
    },
    {
        id: 21,
        on: false,
        word: "umbrella",
        emoji: "☂️",
    },
    {
        id: 22,
        on: false,
        word: "violin",
        emoji: "🎻",
    },
    {
        id: 23,
        on: false,
        word: "whale",
        emoji: "🐋",
    },
    {
        id: 24,
        on: false,
        word: "xylophone",
        emoji: "🎹",
    },
    {
        id: 25,
        on: false,
        word: "yoyo",
        emoji: "🪀",
    },
    {
        id: 26,
        on: false,
        word: "zebra",
        emoji: "🦓",
    },
];
